export type SimpedesUmiApplicationDetail = {
	id: string;
	idNo: string;
	custName: string;
	cellPhoneNumber: string;
	dateOfBirth: string;
	placeOfBirth: string;
	sex: string;
	religion: string;
	maritalStatus: string;
	motherName: string;
	education: string;
	workTypeId: string;
	workPositionId: string;
	workingPosition: string;
	fieldWork: string;
	typeOfWork: string;
	businessType: string;
	addressDom: string;
	address: string;
	partnerId: number;
	partnerName: string;
	status: string;
	ktpImagePath: string;
	selfiePath: string;
	createdAt: string;
	updatedAt: string;
};
